# Generated by Django 4.0.3 on 2022-03-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproduct',
            name='percentage_reduc',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='infoproduct',
            name='quantitySold',
            field=models.IntegerField(default='0'),
        ),
    ]
