# Generated by Django 4.0.3 on 2022-03-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0002_infoproduct_percentage_reduc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonneeHisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateT', models.DateTimeField(auto_now_add=True)),
                ('typeT', models.CharField(blank=True, default='', max_length=100)),
                ('valeurT', models.FloatField(default='0')),
            ],
            options={
                'ordering': ('dateT',),
            },
        ),
    ]
