# Generated by Django 4.0.3 on 2022-03-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0004_alter_donneehisto_datet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneehisto',
            name='dateT',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
