# Generated by Django 4.0.3 on 2022-03-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0006_alter_donneehisto_datet'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneehisto',
            name='category',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='donneehisto',
            name='nameProd',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donneehisto',
            name='quantityT',
            field=models.IntegerField(default='0'),
        ),
    ]
